dist: trusty
language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn run clean
script:
  - yarn run test
  - yarn run lint
before_deploy:
  - yarn run clean
  - yarn run build
